<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>twig</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(&lt;(?i:(head|table|tr|div|style|script|ul|ol|form|dl))\b.*?&gt;|{% (autoescape|block|filter|for|if|macro|set|trans))</string>
	<key>foldingStopMarker</key>
	<string>(&lt;/(?i:(head|table|tr|div|style|script|ul|ol|form|dl))&gt;|{% (endautoescape|endblock|endfilter|endfor|endif|endmacro|endset|endtrans) %})</string>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>HTML (Twig)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{#</string>
			<key>end</key>
			<string>#}</string>
			<key>name</key>
			<string>comment.block.twig</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{{</string>
			<key>end</key>
			<string>}}</string>
			<key>name</key>
			<string>variable.other.twig</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(((?&lt;=filter\s)|\|)(capitalize|e|encoding|escape|even|keys|length|lower|odd|reverse|safe|sort|striptags|title|upper)(\b|\|))</string>
					<key>name</key>
					<string>support.function.filter.variable.twig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((?&lt;=filter\s)|\|)(cycle|date|default|format|in|range)(?=\(.+?\))</string>
					<key>name</key>
					<string>support.function.filter.variable.twig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((?&lt;=filter\s)|\|)(join)(?=\(.+?\)|)</string>
					<key>name</key>
					<string>support.function.filter.variable.twig</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>({%)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.tagbraces.twig</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(%})</string>
			<key>name</key>
			<string>meta.scope.twig</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(autoescape|block|debug|else|elseif|endautoescape|endblock|endfilter|endfor|endif|endmacro|endset|endtrans|extends|filter|for|if|import|include|macro|plural|sandboxed|set|trans)\b</string>
					<key>name</key>
					<string>keyword.control.twig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\s(\?|:|and|as|in|not|or|with)\s</string>
					<key>name</key>
					<string>keyword.operator.twig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((=|&gt;|&lt;)=|!=|&lt;|&gt;|\+|-|~|\*\*?|%|//?|\.\.)</string>
					<key>name</key>
					<string>keyword.operator.twig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(((?&lt;=filter\s)|\|)(capitalize|e|encoding|escape|even|keys|length|lower|odd|reverse|safe|sort|striptags|title|upper)(\b|\|))</string>
					<key>name</key>
					<string>support.function.filter.twig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((?&lt;=filter\s)|\|)(cycle|date|default|format|in|range)(?=\(.+?\))</string>
					<key>name</key>
					<string>support.function.filter.twig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((?&lt;=filter\s)|\|)(join)(?=\(.+?\)|)</string>
					<key>name</key>
					<string>support.function.filter.twig</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=macro\s)([a-zA-Z0-9_]+)\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.twig</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.argument.twig</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\s*([a-zA-Z0-9_]+)\s*(?=,)</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.argument.twig</string>
								</dict>
							</dict>
							<key>match</key>
							<string>,\s*([a-zA-Z0-9_]+)\s*</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.twig</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.twig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[a-zA-Z_]+</string>
					<key>name</key>
					<string>string.unquoted.twig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[0-9]+(\.[0-9]+)?</string>
					<key>name</key>
					<string>constant.numeric.twig</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.twig</string>
	<key>uuid</key>
	<string>C220B028-86FF-44CB-8A59-27937FC83730</string>
</dict>
</plist>
